[package]
name = "gba-joyboot-client"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
enum-primitive-derive = "0.3.0"
num = "0.4.3"
num-derive = "0.4.2"
num-traits = "0.2.19"

[dependencies.async-std]
version = "1.13.0"
features = ["attributes"]
